package com.jassuncao.docmap.domain.project;

import com.jassuncao.docmap.domain.attribute.Attribute;
import com.jassuncao.docmap.domain.entity.Entity;
import org.apache.commons.lang3.StringUtils;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * @author jonathas.assuncao - jaa020399@gmail.com
 * 15/09/2021
 */
public class HibernateData {

    private final List<? extends Attribute> attributes;
    private final Entity entity;
    private final Project project;

    public HibernateData(Project project, Entity entity, List<? extends Attribute> attributes) {
        this.project = project;
        this.entity = entity;
        this.attributes = attributes;
    }

    public Map<String, Object> getParams() {
        final Map<String, Object> params = new HashMap<>();
        params.put("package", pack());
        params.put("headers", header(project, entity));
        params.put("entity", Normalize.dataBaseForm(entity.getAlias()));
        params.put("className", Normalize.classForm(entity.getAlias()));
        params.put("attributes", attributes.stream().map(HibernateAttributeData::new).collect(Collectors.toList()));
        return params;
    }

    private String pack() {
        return new StringBuilder()
                .append("com.")
                .append(Normalize.packageForm(project.getName()))
                .append(".")
                .append(Normalize.packageForm(entity.getAlias()))
                .toString();
    }

    private List<String> header(Project project, Entity entity) {
        final String safeValue = new StringBuilder()
                .append(StringUtils.defaultIfEmpty(project.getDescription(), StringUtils.EMPTY))
                .append(StringUtils.LF)
                .append(StringUtils.defaultIfEmpty(entity.getDescription(), StringUtils.EMPTY))
                .toString();
        final List<String> description = Normalize.splitPreserveTokens(safeValue, 120);
        description.add(StringUtils.EMPTY);
        description.add("Generated by docMap");
        return description;
    }
}
